% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Oct-2023 22:22:19
%  MATLAB version: 9.14.0.2239454 (R2023a) Update 1
% -------------------------------------------------------------------
                                                

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [26.499999999999996 13.300000000000006 2.2999999999999963];
smiData.RigidTransform(1).angle = 0;
smiData.RigidTransform(1).axis = [0 0 0];
smiData.RigidTransform(1).ID = ['B[Revolute Joint 1-1:-:Motor Attacher-' ...
                                '1]'];
smiData.RigidTransform(1).ID = convertCharsToStrings( ...
  smiData.RigidTransform(1).ID);
smiData.RigidTransform(2).translation = ...
  [6.9999999999998188 -14.999999999999989 26.5000000000002];
smiData.RigidTransform(2).angle = 2.094395102393197;
smiData.RigidTransform(2).axis = [-0.57735026918962462 -0.57735026918962629 ...
                                  -0.57735026918962629];
smiData.RigidTransform(2).ID = ['F[Revolute Joint 1-1:-:Motor Attacher-' ...
                                '1]'];
smiData.RigidTransform(2).ID = convertCharsToStrings( ...
  smiData.RigidTransform(2).ID);
smiData.RigidTransform(3).translation = ...
  [26.499999999999996 -13.299999999999992 2.2999999999999963];
smiData.RigidTransform(3).angle = 0;
smiData.RigidTransform(3).axis = [0 0 0];
smiData.RigidTransform(3).ID = ['B[Revolute Joint 1-1:-:Motor Attacher-' ...
                                '2]'];
smiData.RigidTransform(3).ID = convertCharsToStrings( ...
  smiData.RigidTransform(3).ID);
smiData.RigidTransform(4).translation = ...
  [6.9999999999991829 -15.000000000000039 -26.499999999999432];
smiData.RigidTransform(4).angle = 2.0943951023932024;
smiData.RigidTransform(4).axis = [-0.57735026918962162 0.57735026918962784 ...
                                  0.57735026918962784];
smiData.RigidTransform(4).ID = ['F[Revolute Joint 1-1:-:Motor Attacher-' ...
                                '2]'];
smiData.RigidTransform(4).ID = convertCharsToStrings( ...
  smiData.RigidTransform(4).ID);
smiData.RigidTransform(5).translation = ...
  [-4.2488795325205873 0.0012060105149258593 174.72337649086273];
smiData.RigidTransform(5).angle = 3.1415926535897927;
smiData.RigidTransform(5).axis = [1 0 0];
smiData.RigidTransform(5).ID = 'B[Base Frame-1:-:Revolute Joint 1-1]';
smiData.RigidTransform(5).ID = convertCharsToStrings( ...
  smiData.RigidTransform(5).ID);
smiData.RigidTransform(6).translation = ...
  [-2.0900793404300832E-10 2.6917710312223841E-10 100.52337649086292];
smiData.RigidTransform(6).angle = 3.1415926535897931;
smiData.RigidTransform(6).axis = [1 1.6693561202785655E-34 1.9306492095300014E-17 ...
                                  ];
smiData.RigidTransform(6).ID = 'F[Base Frame-1:-:Revolute Joint 1-1]';
smiData.RigidTransform(6).ID = convertCharsToStrings( ...
  smiData.RigidTransform(6).ID);
smiData.RigidTransform(7).translation = ...
  [141.9987144307984 -4.5000000000000036 7.5000000000371365];
smiData.RigidTransform(7).angle = 2.6152034964104449E-13;
smiData.RigidTransform(7).axis = [-0 -1 0];
smiData.RigidTransform(7).ID = ['B[Revolute Joint 2-1:-:Revolute Joint ' ...
                                '3-1]'];
smiData.RigidTransform(7).ID = convertCharsToStrings( ...
  smiData.RigidTransform(7).ID);
smiData.RigidTransform(8).translation = ...
  [7.90758569735317E-11 2.2559731860383181E-12 13.700000000054212];
smiData.RigidTransform(8).angle = 4.241026750550038E-15;
smiData.RigidTransform(8).axis = [0.28292908039489145 0.95914083192558364 ...
                                  5.7544124116685388E-16];
smiData.RigidTransform(8).ID = ['F[Revolute Joint 2-1:-:Revolute Joint ' ...
                                '3-1]'];
smiData.RigidTransform(8).ID = convertCharsToStrings( ...
  smiData.RigidTransform(8).ID);
smiData.RigidTransform(9).translation = ...
  [-50.001285569197641 12.500000000000011 -7.5000000000130793];
smiData.RigidTransform(9).angle = 3.1415926535897931;
smiData.RigidTransform(9).axis = [1 0 0];
smiData.RigidTransform(9).ID = 'B[Revolute Joint 2-1:-:Bushing-1]';
smiData.RigidTransform(9).ID = convertCharsToStrings( ...
  smiData.RigidTransform(9).ID);
smiData.RigidTransform(10).translation = ...
  [16.857888407269783 48.705134810904426 -3.5980178836325649E-9];
smiData.RigidTransform(10).angle = 6.5552438757085837E-13;
smiData.RigidTransform(10).axis = [0.15555598137333029 0.98782707831835626 ...
                                   5.0364728798961954E-14];
smiData.RigidTransform(10).ID = 'F[Revolute Joint 2-1:-:Bushing-1]';
smiData.RigidTransform(10).ID = convertCharsToStrings( ...
  smiData.RigidTransform(10).ID);
smiData.RigidTransform(11).translation = ...
  [-1.9428902930940239E-12 0 7.5000000000000133];
smiData.RigidTransform(11).angle = 2.6152034964104449E-13;
smiData.RigidTransform(11).axis = [-0 -1 0];
smiData.RigidTransform(11).ID = 'B[Revolute Joint 2-1:-:Servo Motor-1]';
smiData.RigidTransform(11).ID = convertCharsToStrings( ...
  smiData.RigidTransform(11).ID);
smiData.RigidTransform(12).translation = ...
  [2.8477585338080473 40.0761319621948 36.350049999983511];
smiData.RigidTransform(12).angle = 2.0943951023931962;
smiData.RigidTransform(12).axis = [-0.577350269189626 -0.5773502691896254 ...
                                   -0.577350269189626];
smiData.RigidTransform(12).ID = 'F[Revolute Joint 2-1:-:Servo Motor-1]';
smiData.RigidTransform(12).ID = convertCharsToStrings( ...
  smiData.RigidTransform(12).ID);
smiData.RigidTransform(13).translation = ...
  [0 17.500000000000014 42.092287702679961];
smiData.RigidTransform(13).angle = 2.0943951023931957;
smiData.RigidTransform(13).axis = [-0.57735026918962584 -0.57735026918962573 ...
                                   -0.57735026918962573];
smiData.RigidTransform(13).ID = 'B[Revolute Joint 3-1:-:Link 2-1]';
smiData.RigidTransform(13).ID = convertCharsToStrings( ...
  smiData.RigidTransform(13).ID);
smiData.RigidTransform(14).translation = ...
  [-42.092287702672976 5.50000000001647 -81.000000000000938];
smiData.RigidTransform(14).angle = 3.1415926535897905;
smiData.RigidTransform(14).axis = [-9.33281230075522E-16 0.70710678118654824 ...
                                   0.707106781186547];
smiData.RigidTransform(14).ID = 'F[Revolute Joint 3-1:-:Link 2-1]';
smiData.RigidTransform(14).ID = convertCharsToStrings( ...
  smiData.RigidTransform(14).ID);
smiData.RigidTransform(15).translation = ...
  [0 0 -10.000000000000044];
smiData.RigidTransform(15).angle = 3.1415926535897931;
smiData.RigidTransform(15).axis = [1 0 0];
smiData.RigidTransform(15).ID = 'B[Revolute Joint 4-1:-:Link 2-1]';
smiData.RigidTransform(15).ID = convertCharsToStrings( ...
  smiData.RigidTransform(15).ID);
smiData.RigidTransform(16).translation = ...
  [9.4999999999720188 -3.6710190443045576E-11 77.00000000000675];
smiData.RigidTransform(16).angle = 2.0943951023931957;
smiData.RigidTransform(16).axis = [0.577350269189626 0.57735026918962573 ...
                                   0.57735026918962551];
smiData.RigidTransform(16).ID = 'F[Revolute Joint 4-1:-:Link 2-1]';
smiData.RigidTransform(16).ID = convertCharsToStrings( ...
  smiData.RigidTransform(16).ID);
smiData.RigidTransform(17).translation = ...
  [52.000000000000043 -9.5000000000000089 0];
smiData.RigidTransform(17).angle = 2.0943951023931953;
smiData.RigidTransform(17).axis = [0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(17).ID = ['B[Revolute Joint 4-1:-:End Effector-1' ...
                                 ']'];
smiData.RigidTransform(17).ID = convertCharsToStrings( ...
  smiData.RigidTransform(17).ID);
smiData.RigidTransform(18).translation = ...
  [29.100000000003391 16.000000000002167 1.6211032516366686E-11];
smiData.RigidTransform(18).angle = 2.0943951023932041;
smiData.RigidTransform(18).axis = [0.57735026918962062 -0.57735026918962817 ...
                                   0.57735026918962851];
smiData.RigidTransform(18).ID = ['F[Revolute Joint 4-1:-:End Effector-1' ...
                                 ']'];
smiData.RigidTransform(18).ID = convertCharsToStrings( ...
  smiData.RigidTransform(18).ID);
smiData.RigidTransform(19).translation = ...
  [2.8477585338481104 13.076131962468708 36.35005000000001];
smiData.RigidTransform(19).angle = 2.0943951023931953;
smiData.RigidTransform(19).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(19).ID = 'B[Servo Motor-1:-:Bushing-1]';
smiData.RigidTransform(19).ID = convertCharsToStrings( ...
  smiData.RigidTransform(19).ID);
smiData.RigidTransform(20).translation = ...
  [2.6984912082639312E-9 -1.632901813763965E-9 11.999999996120909];
smiData.RigidTransform(20).angle = 3.1415926535894734;
smiData.RigidTransform(20).axis = [-1 -4.0403702781242478E-26 2.525380245306548E-13 ...
                                   ];
smiData.RigidTransform(20).ID = 'F[Servo Motor-1:-:Bushing-1]';
smiData.RigidTransform(20).ID = convertCharsToStrings( ...
  smiData.RigidTransform(20).ID);
smiData.RigidTransform(21).translation = ...
  [15.000000000000014 0 35];
smiData.RigidTransform(21).angle = 2.0943951023931953;
smiData.RigidTransform(21).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(21).ID = 'B[Motor Attacher-1:-:Servo Motor-1]';
smiData.RigidTransform(21).ID = convertCharsToStrings( ...
  smiData.RigidTransform(21).ID);
smiData.RigidTransform(22).translation = ...
  [17.547758533846185 12.576131962706178 14.550049999688667];
smiData.RigidTransform(22).angle = 3.1415926535897767;
smiData.RigidTransform(22).axis = [8.3266726846886756E-15 -0.70710678118654757 ...
                                   0.70710678118654757];
smiData.RigidTransform(22).ID = 'F[Motor Attacher-1:-:Servo Motor-1]';
smiData.RigidTransform(22).ID = convertCharsToStrings( ...
  smiData.RigidTransform(22).ID);
smiData.RigidTransform(23).translation = ...
  [15.000000000000016 0 35];
smiData.RigidTransform(23).angle = 2.0943951023931953;
smiData.RigidTransform(23).axis = [0.57735026918962584 0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(23).ID = 'B[Motor Attacher-2:-:Servo Motor-3]';
smiData.RigidTransform(23).ID = convertCharsToStrings( ...
  smiData.RigidTransform(23).ID);
smiData.RigidTransform(24).translation = ...
  [-11.852241466151526 12.576131962525615 84.550050000321747];
smiData.RigidTransform(24).angle = 1.5707963267948961;
smiData.RigidTransform(24).axis = [1 -1.6368213881778355E-14 1.6171952324442881E-14 ...
                                   ];
smiData.RigidTransform(24).ID = 'F[Motor Attacher-2:-:Servo Motor-3]';
smiData.RigidTransform(24).ID = convertCharsToStrings( ...
  smiData.RigidTransform(24).ID);
smiData.RigidTransform(25).translation = ...
  [51.513128535424045 65.807122274565231 78.427567996598341];
smiData.RigidTransform(25).angle = 0;
smiData.RigidTransform(25).axis = [0 0 0];
smiData.RigidTransform(25).ID = 'RootGround[Base Frame-1]';
smiData.RigidTransform(25).ID = convertCharsToStrings( ...
  smiData.RigidTransform(25).ID);
smiData.Solid = struct;
smiData.Solid(1).mass = 1.53316863574305E-13;
smiData.Solid(1).CoM = [66.07585489452255 -0.68248123034025621 -0.060691721841793167 ...
                        ];
smiData.Solid(1).MoI = [0 0 0];
smiData.Solid(1).PoI = [0 0 0];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Revolute Joint 2*:*Default';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);
smiData.Solid(2).mass = 1.124626804251096E-12;
smiData.Solid(2).CoM = [2.8476957816965851 -12.053712929011333 53.024946012204964 ...
                        ];
smiData.Solid(2).MoI = [8.3447929099856193E-10 5.8776427455524821E-10 5.9939505829273182E-10 ...
                        ];
smiData.Solid(2).PoI = [0 0 0];
smiData.Solid(2).color = [0.25098039215686274 0.25098039215686274 0.25098039215686274 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Servo Motor*:*Default';
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);
smiData.Solid(3).mass = 5.8082048900423213E-12;
smiData.Solid(3).CoM = [-3.7812219828482529 0.0060418053292658905 29.633755019860832 ...
                        ];
smiData.Solid(3).MoI = [7.631370657460713E-9 7.4853423621230032E-9 1.1058625022146746E-8 ...
                        ];
smiData.Solid(3).PoI = [0 0 0];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Base Frame*:*Default';
smiData.Solid(3).ID = convertCharsToStrings(smiData.Solid(3).ID);
smiData.Solid(4).mass = 1.4002676957465425E-13;
smiData.Solid(4).CoM = [-0.0751696189259377 0.33355434764336278 -13.633706491550109 ...
                        ];
smiData.Solid(4).MoI = [0 0 0];
smiData.Solid(4).PoI = [0 0 0];
smiData.Solid(4).color = [0.25098039215686274 0.25098039215686274 0.25098039215686274 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Link 2*:*Default';
smiData.Solid(4).ID = convertCharsToStrings(smiData.Solid(4).ID);
smiData.Solid(5).mass = 2.06042604896082E-13;
smiData.Solid(5).CoM = [-0.1725491909095028 5.6936791429444785E-9 0.0064769379026456972 ...
                        ];
smiData.Solid(5).MoI = [0 0 0];
smiData.Solid(5).PoI = [0 0 0];
smiData.Solid(5).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Revolute Joint 1*:*Default';
smiData.Solid(5).ID = convertCharsToStrings(smiData.Solid(5).ID);
smiData.Solid(6).mass = 3.2330582638054785E-14;
smiData.Solid(6).CoM = [-14.122982293052464 6.3159591636733 1.1013272619672785 ...
                        ];
smiData.Solid(6).MoI = [0 0 0];
smiData.Solid(6).PoI = [0 0 0];
smiData.Solid(6).color = [0.25098039215686274 0.25098039215686274 0.25098039215686274 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Revolute Joint 3*:*Default';
smiData.Solid(6).ID = convertCharsToStrings(smiData.Solid(6).ID);
smiData.Solid(7).mass = 3.1257230364918482E-14;
smiData.Solid(7).CoM = [23.72786979736636 0.31605832812207879 -1.9110563027618879 ...
                        ];
smiData.Solid(7).MoI = [0 0 0];
smiData.Solid(7).PoI = [0 0 0];
smiData.Solid(7).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Revolute Joint 4*:*Default';
smiData.Solid(7).ID = convertCharsToStrings(smiData.Solid(7).ID);
smiData.Solid(8).mass = 2.133051878101551E-14;
smiData.Solid(8).CoM = [11.561485016654817 -9.6619423286604516 -6.2407310755690629E-11 ...
                        ];
smiData.Solid(8).MoI = [0 0 0];
smiData.Solid(8).PoI = [0 0 0];
smiData.Solid(8).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'Motor Attacher*:*Default';
smiData.Solid(8).ID = convertCharsToStrings(smiData.Solid(8).ID);
smiData.Solid(9).mass = 4.12637037987977E-14;
smiData.Solid(9).CoM = [7.5322367321268828 9.49856220477288 -3.79204126055593E-12 ...
                        ];
smiData.Solid(9).MoI = [0 0 0];
smiData.Solid(9).PoI = [0 0 0];
smiData.Solid(9).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(9).opacity = 1;
smiData.Solid(9).ID = 'End Effector*:*Default';
smiData.Solid(9).ID = convertCharsToStrings(smiData.Solid(9).ID);
smiData.Solid(10).mass = 2.3125137036938327E-14;
smiData.Solid(10).CoM = [8.9842521395227335E-6 -0.088737759321309492 4.5975126644071045 ...
                         ];
smiData.Solid(10).MoI = [0 0 0];
smiData.Solid(10).PoI = [0 0 0];
smiData.Solid(10).color = [0.25098039215686274 0.25098039215686274 0.25098039215686274 ...
                           ];
smiData.Solid(10).opacity = 1;
smiData.Solid(10).ID = 'Bushing*:*Default';
smiData.Solid(10).ID = convertCharsToStrings(smiData.Solid(10).ID);
smiData.CylindricalJoint = struct;
smiData.CylindricalJoint.Rz = struct;
smiData.CylindricalJoint.Rz.Pos = 89.232256849013609;
smiData.CylindricalJoint.Pz = struct;
smiData.CylindricalJoint.Pz.Pos = 0;
smiData.CylindricalJoint.ID = '[Revolute Joint 2-1:-:Servo Motor-1]';
smiData.CylindricalJoint.ID = convertCharsToStrings( ...
  smiData.CylindricalJoint.ID);
smiData.PlanarJoint = struct;
smiData.PlanarJoint.Rz = struct;
smiData.PlanarJoint.Rz.Pos = 123.12772762978955;
smiData.PlanarJoint.Px = struct;
smiData.PlanarJoint.Px.Pos = 0;
smiData.PlanarJoint.Py = struct;
smiData.PlanarJoint.Py.Pos = 0;
smiData.PlanarJoint.ID = '[Revolute Joint 2-1:-:Bushing-1]';
smiData.PlanarJoint.ID = convertCharsToStrings( ...
  smiData.PlanarJoint.ID);
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -16.486130022138731;
smiData.RevoluteJoint(1).ID = '[Base Frame-1:-:Revolute Joint 1-1]';
smiData.RevoluteJoint(1).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(1).ID);
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = -97.605709337373682;
smiData.RevoluteJoint(2).ID = ['[Revolute Joint 2-1:-:Revolute Joint 3-' ...
                               '1]'];
smiData.RevoluteJoint(2).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(2).ID);
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = -51.911023762702513;
smiData.RevoluteJoint(3).ID = '[Revolute Joint 4-1:-:Link 2-1]';
smiData.RevoluteJoint(3).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(3).ID);
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = 147.64001552119683;
smiData.RevoluteJoint(4).ID = '[Servo Motor-1:-:Bushing-1]';
smiData.RevoluteJoint(4).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(4).ID);

